spring:
  datasource:
    # 1. 한글 인코딩 규격 안정화 및 MySQL 8.x 호환성을 위한 옵션 추가
    url: jdbc:mysql://db:3306/locode-db?serverTimezone=Asia/Seoul&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        format_sql: true

server:
  forward-headers-strategy: framework